---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 100m
            memory: "128M"
          limits:
            cpu: 200m
            memory: "256M"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"