---
apiVersion: v1
kind: Service
metadata:
  name: app-1-app
  namespace: flux-gitops-app1
  labels:
    app: app-1-app
spec:
  type: LoadBalancer
  ports:
  - name: app-1-app-http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-1-app